trigger:
  branches:
    include:
    - main
  paths:
    include:
    - '**/*.py'
    - '**/*.java'
    - '**/*.js'
    - '**/*.cpp'

pool:
  name: 'Default'
  demands:
    - agent.name -equals MAANAS

steps:
- script: |
    echo Detecting programming languages in the repository...
    for /f "delims=" %%f in ('git ls-files') do (
      set file=%%f
      REM Check for Python files
      echo %%f | findstr /i "\.py$" >nul && (
        echo Python file detected: %%f
        python --version
        python %%f
      )

      REM Check for Java files
      echo %%f | findstr /i "\.java$" >nul && (
        echo Java file detected: %%f
        javac %%f
        java %%~nf
      )

      REM Check for JavaScript files
      echo %%f | findstr /i "\.js$" >nul && (
        echo JavaScript file detected: %%f
        node %%f
      )

      REM Check for C++ files
      echo %%f | findstr /i "\.cpp$" >nul && (
        echo C++ file detected: %%f
        g++ %%f -o %%~nf.exe
        %%~nf.exe
      )
    )
  displayName: 'Detect and Execute Scripts'
