trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '**/*.py'
      - '**/*.java'
      - '**/*.html'

pool:
  name: 'Default'
  demands:
    - agent.name -equals MAANAS

jobs:
- job: ExecuteScripts
  displayName: 'Execute Python and Java Scripts'
  pool:
    name: 'Default'
    demands:
      - agent.name -equals MAANAS
      
  steps:


  - script: |
      echo "Executing Python script..."
      python Python_File.py 
    displayName: 'Run Python Script'

  - script: |
      echo "Compiling Java program..."
      javac Java_File.java  
      echo "Executing Java program..."
      java Java_File  # Run Java program (Class name with no .class extension)
    displayName: 'Run Java Program'

  - script: |
      echo "Opening HTML file..."
      start index.html  # Open HTML file in browser; use 'xdg-open' for Linux
    displayName: 'Open HTML File'
