trigger:
  branches:
    include:
    - main
  paths:
    include:
    - '**/*.py'
    - '**/*.java'
    - '**/*.js'
    - '**/*.cpp'

pool:
  name: 'Default'
  demands:
    - agent.name -equals MAANAS

steps:
- script: |
    echo Detecting programming languages in the repository...
    
    REM List all files and filter out the pipeline YAML file
    git ls-files | findstr /v "azure-pipelines.yml" > file_list.txt

    REM Check if file_list.txt is empty
    if not exist file_list.txt (
      echo No files to process.
      exit /b
    )

    REM Iterate over the files in file_list.txt
    for /f %%f in (file_list.txt) do (
      echo Processing file: %%f
      set file=%%f
      REM Check for Python files
      echo %%f | findstr /i "\.py$" >nul && (
        echo Python file detected: %%f
        python --version
        REM Attempt to run the Python script and capture output/error
        echo Running Python script: %%f
        python %%f > output.log 2>&1
        IF %ERRORLEVEL% NEQ 0 (
          echo Failed to run Python file: %%f
          echo Output log: 
          type output.log
        ) ELSE (
          echo Successfully executed Python file: %%f
        )
      )

      REM Check for Java files
      echo %%f | findstr /i "\.java$" >nul && (
        echo Java file detected: %%f
        javac %%f || echo Failed to compile Java file: %%f
        java %%~nf || echo Failed to execute Java file: %%~nf
      )

      REM Check for JavaScript files
      echo %%f | findstr /i "\.js$" >nul && (
        echo JavaScript file detected: %%f
        node %%f || echo Failed to run JavaScript file: %%f
      )

      REM Check for C++ files
      echo %%f | findstr /i "\.cpp$" >nul && (
        echo C++ file detected: %%f
        g++ %%f -o %%~nf.exe || echo Failed to compile C++ file: %%f
        %%~nf.exe || echo Failed to execute C++ file: %%~nf.exe
      )
    )
  displayName: 'Detect and Execute Scripts'
