trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '**/*.py'
      - '**/*.java'
      - '**/*.html'

pool:
  name: 'Default'
  demands:
    - agent.name -equals MAANAS

jobs:
- job: ExecuteScripts
  displayName: 'Execute Python and Java Scripts'
  pool:
    name: 'Default'
    demands:
      - agent.name -equals MAANAS
      
  steps:
  - script: |
      echo "Executing Python script..."
      python path/to/your_script.py  # Update with your Python file path
    displayName: 'Run Python Script'

  - script: |
      echo "Executing Java program..."
      javac path/to/your_program.java  # Compile Java file
      java -cp path/to your_program  # Run Java file (without .class)
    displayName: 'Run Java Program'

  - script: |
      echo "Opening HTML file..."
      start path/to/your_file.html   # Opens HTML file; use 'xdg-open' for Linux or 'start' for Windows
    displayName: 'Open HTML File'
