trigger:
  branches:
    include:
    - main
  paths:
    include:
    - '**/*.py'
    - '**/*.java'
    - '**/*.html'

pool:
  name: 'Default'
  demands:
    - agent.name -equals MAANAS

steps:
- script: |
    echo Detecting programming languages and HTML files in the repository...

    REM List all files and filter out the pipeline YAML file
    git ls-files | findstr /v "azure-pipelines.yml" > file_list.txt
    echo File list generated:
    type file_list.txt

    REM Check if file_list.txt is empty
    if not exist file_list.txt (
      echo No files to process.
      exit /b 0
    )

    REM Enable delayed variable expansion
    setlocal enabledelayedexpansion

    REM Check if Java and Python are available
    echo Checking Java and Python versions...
    java -version
    IF !ERRORLEVEL! NEQ 0 (
      echo Java is not installed or not found in the PATH.
      exit /b 1
    )
    python --version
    IF !ERRORLEVEL! NEQ 0 (
      echo Python is not installed or not found in the PATH.
      exit /b 1
    )

    REM Iterate over the files in file_list.txt
    for /f %%f in (file_list.txt) do (
      echo Processing file: %%f
      
      REM Check for Python files
      echo %%f | findstr /i "\.py$" >nul && (
        echo Python file detected: %%f
        REM Attempt to run the Python script and capture output/error
        echo Running Python script: %%f
        python %%f > output.log 2>&1
        IF !ERRORLEVEL! NEQ 0 (
          echo Failed to run Python file: %%f
          echo Output log:
          type output.log
          exit /b 1
        ) ELSE (
          echo Successfully executed Python file: %%f
        )
      )

      REM Check for Java files
      echo %%f | findstr /i "\.java$" >nul && (
        echo Java file detected: %%f
        REM Compile Java file
        javac %%f > javac_output.log 2>&1
        IF !ERRORLEVEL! NEQ 0 (
          echo Failed to compile Java file: %%f
          echo Output log:
          type javac_output.log
          exit /b 1
        )
        REM Run the compiled Java file (using file name without extension)
        java %%~nf > java_output.log 2>&1
        IF !ERRORLEVEL! NEQ 0 (
          echo Failed to execute Java file: %%~nf
          echo Output log:
          type java_output.log
          exit /b 1
        ) ELSE (
          echo Successfully executed Java file: %%~nf
        )
      )

      REM Check for HTML files
      echo %%f | findstr /i "\.html$" >nul && (
        echo HTML file detected: %%f
        REM HTML files are typically static and don't need execution, just log it.
        echo HTML file processed: %%f
      )
    )
  displayName: 'Detect and Execute Python, Java, and HTML Files'
