# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'
  demands:
    - agent.name -equals MAANAS   

steps:
- script: |
    echo Setting up Python environment...
    python --version  # Check Python version
    pip install --upgrade pip  # Upgrade pip
    # pip install -r requirements.txt  # Install dependencies from requirements.txt (if you have one)
  displayName: 'Set up Python environment'

- script: |
    echo Running Python script...
    python Python_File.py  
  displayName: 'Run Python script'

