trigger:
  branches:
    include:
    - main
  paths:
    include:
    - '**/*.py'
    - '**/*.java'
    - '**/*.html'

pool:
  name: 'Default'
  demands:
    - agent.name -equals MAANAS

steps:
- script: |
    echo Detecting programming languages and HTML files in the repository...
    
    REM List all files and filter out the pipeline YAML file
    git ls-files | findstr /v "azure-pipelines.yml" > file_list.txt
    echo File list generated:
    type file_list.txt

    REM Check if file_list.txt is empty
    if not exist file_list.txt (
      echo No files to process.
      exit /b 0
    )

    REM Enable delayed variable expansion
    setlocal enabledelayedexpansion

    REM Check if Java and Python are available
    echo Checking Java and Python versions...
    java -version
    IF !ERRORLEVEL! NEQ 0 (
      echo Java is not installed or not found in the PATH.
      exit /b 1
    )
    python --version
    IF !ERRORLEVEL! NEQ 0 (
      echo Python is not installed or not found in the PATH.
      exit /b 1
    )

    REM Iterate over the files in file_list.txt
    for /f %%f in (file_list.txt) do (
      echo Processing file: %%f
      REM Log the file type being processed
      echo Processing file: %%f >> process_log.txt

      REM Check for Python files
      echo %%f | findstr /i "\.py$" >nul && (
        echo Python file detected: %%f
        REM Attempt to run the Python script and capture output/error
        echo Running Python script: %%f
        python %%f > output.log 2>&1
        IF !ERRORLEVEL! NEQ 0 (
          echo Failed to run Python file: %%f
          echo Output log:
          type output.log
          exit /b 1
        ) ELSE (
          echo Successfully executed Python file: %%f
          echo Output of Python file:
          type output.log
          echo Success: Python file executed: %%f >> process_log.txt
        )
      )

      REM Check for Java files
      echo %%f | findstr /i "\.java$" >nul && (
        echo Java file detected: %%f
        REM Compile Java file
        javac %%f
        IF !ERRORLEVEL! NEQ 0 (
          echo Failed to compile Java file: %%f
          exit /b 1
        )
        REM Run the compiled Java file (using file name without extension)
        echo Running Java file: %%~nf
        java %%~nf > output.log 2>&1
        IF !ERRORLEVEL! NEQ 0 (
          echo Failed to execute Java file: %%~nf
          exit /b 1
        ) ELSE (
          echo Successfully executed Java file: %%~nf
          echo Output of Java file:
          type output.log
          echo Success: Java file executed: %%~nf >> process_log.txt
        )
      )

      REM Check for HTML files (optional)
      echo %%f | findstr /i "\.html$" >nul && (
        echo HTML file detected: %%f
        REM HTML file cannot be opened in the browser from the pipeline directly, 
        REM but you can print a message about opening it locally
        echo To view the HTML file, open it in your browser: %%f
        REM Optionally, you can validate the HTML content or run tests here
        echo Successfully processed HTML file: %%f >> process_log.txt
      )
    )

    REM Show contents of the process log for review
    type process_log.txt
  displayName: 'Detect and Execute Python, Java, and HTML Files'
