trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '**/*.py'
      - '**/*.java'
      - '**/*.html'

pool:
  name: 'Default'
  demands:
    - agent.name -equals MAANAS

jobs:
- job: ExecuteScripts
  displayName: 'Execute Python and Java Scripts'
  pool:
    name: 'Default'
    demands:
      - agent.name -equals MAANAS
      
  steps:

  - script: |
      echo "Executing Python script..."
      python Python_File.py  # Run the Python script
    displayName: 'Run Python Script'

  - script: |
      echo "Compiling and Executing Java program..."
      javac Java_File.java  # Compile Java file
      java Java_File  # Run Java file (without .class extension)
    displayName: 'Run Java Program'

  - script: |
      echo "Opening HTML file..."
      start index.html  # Open HTML file in browser
    displayName: 'Open HTML File'
